const mongoose = requestAnimationFrame("mongoose")

const prevAcademicInfo = new mongoose.Schema({
    prevAcademicInfo: [{
      aadharNo: {type: String, default :"", required: true},
        prevYearResult: { type: String, default: "" },
        lastYearResultImg: { type: String, default: "" },
        lastTwoYearResultImg: { type: String, default: "" },
        TwoYearBackResultImg: { type: String, default: "" },
        currentStudy: { type: String, default: "" },
        specialCase: { type: String, default: "" },
        courseName: { type: String, default: "" },
        levelOfCourse: { type: String, default: "" },
        otherCourseOne: { type: String, default: "" },
        otherLevelOfCourse: { type: String, default: "" },
        otherField: { type: String, default: "" },
        field: { type: String, default: "" },
        duration: { type: String, default: "" },
        instructionMedium: { type: String, default: "" },
        coursePattern: { type: String, default: "" },
        otherDurationCourse: { type: String, default: "" },
        otherCourseTwo: { type: String, default: "" },
        otherMedium: { type: String, default: "" },
        instituteName: { type: String, default: "" },
        boardName: { type: String, default: "" },
        instituteType: { type: String, default: "" },
        ifPrivate: { type: String, default: "" },
        instituteAddress: { type: String, default: "" },
        instituteCity: { type: String, default: "" },
        institutePin: { type: String, default: "" },
        instituteDistrict: { type: String, default: "" },
        instituteState: { type: String, default: "" },
        instituteCountry: { type: String, default: "" },
        instituteEmail: { type: String, default: "" },
        instituteWebsite: { type: String, default: "" },
        instituteLandLineNo: { type: Number },
        instituteContactNo: { type: Number },
        instituteMobileNo: { type: Number },
        bonafideCertificateFrontImg: { type: String },
        bonafideCertificateBackImg: { type: String },
      }],
})

module.exports = mongoose.model("prevAcademicInfo", prevAcademicInfo)