const mongoose = require("mongoose");

// const familyMemberSchema = new mongoose.Schema( {
//   parentStatus: { type: String },
//   parentStatusOneImg: { type: String },
//   parentStatusTwoImg: { type: String },
//   relationWithStudent: { type: String },
//   relationPersonName: { type: String },
//   relationPersonMaritalStatus: { type: String },
//   relationPersonDOB: { type: String },
//   relationPersonGender: { type: String },
//   relationPersonAge: { type: String },
//   relationPersonAadhar: { type: String },
//   relationPersonEducation: { type: String },
//   relationPersonOccupation: { type: String },
//   relationPersonOccupationDetails: { type: String },
//   relationPersonMonthlyIncome: { type: Number },
//   incomeFileFrontImg: { type: String },
//   incomeFileBackImg: { type: String },
//   handiCapped: { type: String },
//   handiCapFileOneImg: { type: String },
//   handiCapFileTwoImg: { type: String },
//   personCity: { type: String },
//   personStudying: { type: String },
// },{ _id: true });

const studentSchema = new mongoose.Schema({
  studentInfo: {
    aadharNo: { type: String },
    lastName: { type: String },
    firstName: { type: String },
    fatherName: { type: String },
    motherName: { type: String },
    guardianName: { type: String },
    dob: { type: Date },
    birthPlace: { type: String },
    gender: { type: String },
    maritalStatus: { type: String },
    spouseName: { type: String },
    StudentMobileNo: { type: Number },
    StudentEmail: { type: String },
    parmanentAddress: { type: String },
    currentAddress: { type: String },
    landMark: { type: String },
    city: { type: String },
    pin: { type: String },
    district: { type: String },
    state: { type: String },
    country: { type: String },
    physicalChallange: { type: String },
    physicalChallangeImg: { type: String },
    orphan: { type: String },
    parentDeathCertificateImg: { type: String },
    addaharFrontImg: { type: String },
    aadharBackImg: { type: String },
    rationFrontImg: { type: String },
    rationBackImg: { type: String },
    electricityBillImg: { type: String },
    category: { type: String },
    zakatFund: { type: Number },
    refferedBy: { type: String },
    refMobileNo: { type: String },
  },
  familyDetails: [{
    parentStatus: { type: String },
    parentStatusOneImg: { type: String },
    parentStatusTwoImg: { type: String },
    relationWithStudent: { type: String },
    relationPersonName: { type: String },
    relationPersonMaritalStatus: { type: String },
    relationPersonDOB: { type: String },
    relationPersonGender: { type: String },
    relationPersonAge: { type: String },
    relationPersonAadhar: { type: String },
    relationPersonEducation: { type: String },
    relationPersonOccupation: { type: String },
    relationPersonOccupationDetails: { type: String },
    relationPersonMonthlyIncome: { type: Number },
    incomeFileFrontImg: { type: String },
    incomeFileBackImg: { type: String },
    handiCapped: { type: String },
    handiCapFileOneImg: { type: String },
    handiCapFileTwoImg: { type: String },
    personCity: { type: String },
    personStudying: { type: String },
  },{   timestamps: true }],
  jamatInfo: {
    ifMemon: { type: String, default: "" },
    ifMotherMomen: { type: String, default: "" },
    memonJamatLetterOne: { type: String, default: "" },
    memonJamatLetterTwo: { type: String, default: "" },
    jamatDetails: { type: String, default: "" },
    belongingJamat: { type: String, default: "" },
    jamatSecretaryName: { type: String, default: "" },
    secretaryMobile: { type: Number, default: 0 },
    secretaryEmail: { type: String, default: "" },
    memonAddress: { type: String, default: "" },
    memonCity: { type: String, default: "" },
    memonPin: { type: String, default: "" },
    memonState: { type: String, default: "" },
    helpFromJamat: { type: String, default: "" },
    jamatReceiveAmount: { type: Number, default: 0 },
    amountReceivePurpose: { type: String, default: "" },
    amountType: { type: String, default: "" },
    deeniyatCourse: { type: String, default: "" },
    courseName: { type: String, default: "" },
    madrashaName: { type: String, default: "" },
    anyOtherCourse: { type: String, default: "" },
  },
  prevAcademicInfo: [
    {
      prevYearResult: { type: String },
      lastYearResultImg: { type: String },
      lastTwoYearResultImg: { type: String },
      TwoYearBackResultImg: { type: String },
      currentStudy: { type: String },
      specialCase: { type: String },
      courseName: { type: String },
      levelOfCourse: { type: String },
      otherCourseOne: { type: String },
      otherLevelOfCourse: { type: String },
      otherField: { type: String },
      field: { type: String },
      duration: { type: String },
      instructionMedium: { type: String },
      coursePattern: { type: String },
      otherDurationCourse: { type: String },
      otherCourseTwo: { type: String },
      otherMedium: { type: String },
      instituteName: { type: String },
      boardName: { type: String },
      instituteType: { type: String },
      ifPrivate: { type: String },
      instituteAddress: { type: String },
      instituteCity: { type: String },
      institutePin: { type: String },
      instituteDistrict: { type: String },
      instituteState: { type: String },
      instituteCountry: { type: String },
      instituteEmail: { type: String },
      instituteWebsite: { type: String },
      instituteLandLineNo: { type: Number },
      instituteContactNo: { type: Number },
      instituteMobileNo: { type: Number },
      bonafideCertificateFrontImg: { type: String },
      bonafideCertificateBackImg: { type: String },
    },
  ],
  othertrustSupport: {
    otherTrustSupport: { type: String },
    trustDetails: [
      {
        trustName: { type: String },
        currentYearAmount: { type: Number, default: 0 },
        lastYearAmount: { type: Number, default: 0 },
        trustState: { type: String },
        trustCity: { type: String },
      },
    ],
    otherContribution: [
      {
        contributionSource: { type: String },
        contributionCurrentyearAmunt: { type: Number, default: 0 },
        contributionLastyearAmunt: { type: Number, default: 0 },
        contributionState: { type: String },
        contributionCity: { type: String },
      },
    ],
    govtScholarshipApply: { type: String },
    scholarAmount: { type: Number, default: 0 },
    scholarYear: { type: Date, default: Date.now },
    scholarName: { type: String },
    applicationId: { type: String },
    applicationPass: { type: String },
  },
  organizationSupportFamily: {
    receivedSupport: { type: String },
    supportFamilyDetails: [
      {
        memberName: { type: String },
        memberId: { type: String },
        course: { type: String },
        amountReceived: { type: Number },
        financialYear: { type: String },
        howManyYearsGet: { type: Number },
      },
    ],
    memberReceiveSupport: { type: String },
    otherSupport: [
      {
        memberName: { type: String },
        memberId: { type: String },
        scheme: { type: String },
        amountreceived: { type: Number },
        financialYear: { type: String },
      },
    ],
  },
  familyDeclaration: {
    courseName: { type: String },
    applicantName: { type: String },
    parentName: { type: String },
    place: { type: String },
    date: { type: Date },
    studentPhoto: { type: String },
    studentSign: { type: String },
    parentSign: { type: String },
  },
  currentAcademicDetails: {
    currentlyStudingIn: { type: String, default: "" },
    currentSpecialCase: { type: String, default: "" },
    currentlyCourseName: { type: String, default: "" },
    currentlyLevelOfCourse: { type: String, default: "" },
    currentlyField: { type: String, default: "" },
    currentlyDuration: { type: String, default: "" },
    currentlyMediumOfInstruction: { type: String, default: "" },
    currentlyPatternOfTheCourse: { type: String, default: "" },
    currentlyInstituteName: { type: String, default: "" },
    currentlyBoardName: { type: String, default: "" },
    currentlyInstitutionType: { type: String, default: "" },
    currentlyIfPrivate: { type: String, default: "" },
    currentlyInstitutionAddress: { type: String, default: "" },
    currentlyInstitutionCity: { type: String, default: "" },
    currentlyInstitutionDistrict: { type: String, default: "" },
    currentlyInstitutionState: { type: String, default: "" },
    currentlyInstitutionCountry: { type: String, default: "" },
    currentlyInstitutionEmail: { type: String, default: "" },
    currentlyInstitutionWebsite: { type: String, default: "" },
    currentlyInstitutionPin: { type: String, default: "" },
    currentlyInstitutionBonafidfrontImg: { type: String, default: "" },
    currentlyInstitutionBonafidBackImg: { type: String, default: "" },
    currentlyInstitutionlandLine: { type: String, default: "" },
    currentlyInstitutionContact: { type: String, default: "" },
    currentlyInstitutionContact: { type: String, default: "" },
    currentlyInstitutionMobile: { type: String, default: "" },
  },
  feesInformation: {
    termFees: { type: String, default: 0 },
    tutionFees: { type: String, default: 0 },
    otherFees: { type: String, default: 0 },
    totalFees: { type: String, default: 0 },
    coachingFees: { type: String, default: 0 },
    hostelFees: { type: String, default: 0 },
    meesFees: { type: String, default: 0 },
    conveance: { type: String, default: 0 },
    bookStationary: { type: String, default: 0 },
    projectInstrument: { type: String, default: 0 },
    anyOther: { type: String, default: 0 },
    totalABC: { type: String, default: 0 },
    ownContribute: { type: String, default: 0 },
    totalABCD: { type: String, default: 0 },
  },
  bankDetails: {
    nameAsPassBook: { type: String, default: "" },
    AcountNO: { type: String, default: "" },
    BankName: { type: String, default: "" },
    Branch: { type: String, default: "" },
    ifsc: { type: String, default: "" },
    passBookFrontImg: { type: String, default: "" },
    passBookBackImg: { type: String, default: "" },
  },
  addedBy: { type: String },
  studentCode: { type: String },
  isConfirm: { type: Boolean, default: false },
  saveAsDraft: { type: Boolean, default: false },
  isDeleted: { type: Boolean, default: false },
  formAcceptStatus: { type: Boolean, default: false },
  updatedStatus: { type: Boolean, default: false },
  createdOn: { type: Date, default: Date.now },
  updatedOn: { type: Date, default: Date.now },
});

module.exports = mongoose.model("studentData", studentSchema);
